AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
Parameters:
  charsetparam:
    Type: String
    Default: 'UTF-8'
    AllowedValues:
      - 'UTF-8'
Resources:
  SendEmailFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: sendEmail/
      Handler: app.lambda_handler
      Runtime: python3.6
      Policies:
        - AmazonSESFullAccess
      Environment:
        Variables:
          CHARSET: !Ref charsetparam
      Events:
        SendEmail:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sendEmail
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SendEmailApi:
    Description: "API Gateway endpoint URL for Prod stage for Send email function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/sendEmail/"
  SendEmailFunction:
    Description: "Send Email Lambda Function ARN"
    Value: !GetAtt SendEmailFunction.Arn
  SendEmailFunctionIamRole:
    Description: "Implicit IAM Role created for Send Email function"
    Value: !GetAtt SendEmailFunction.Arn
